add error checking to makeplugin

diff --git a/plugins/makeplugin b/plugins/makeplugin
--- a/plugins/makeplugin
+++ b/plugins/makeplugin
@@ -1,6 +1,16 @@
 #!/bin/bash
 cc -fPIC -g -c -Wall $1.c plugins.c
+if [[ $? -ne 0 ]]
+then
+	echo "Installation failed!"
+	exit 1
+fi
 cc -shared -Wl,-soname,lib$1.so -o lib$1.so $1.o plugins.o -lc
+if [[ $? -ne 0 ]]
+then
+	echo "Installation failed!"
+	exit 1
+fi
 mv lib$1.so ~/.config/mkvsynth/
 rm $1.o plugins.o
 echo "Installation successful!"
